lib1
DashaKS25/Library pull request #1
Opened 2023-09-03 09:48 UTC by DashaKS25

2023-09-14 22:07 UTC, vickovtu commented on Books/views.py
> +        if action == 'approve':
это ж можно объединить `if action in ['approve', 'decline']:  borrow_request = BorrowRequest.objects.get(pk=request_id) borrow_request.status=action borrow_request.save(update_fields['status'])`

2023-09-14 22:07 UTC, vickovtu commented on Books/views.py
> +class AuthorsCreate(View):
CreateView

2023-09-14 22:07 UTC, vickovtu commented on Books/views.py
> +class GenreCreate(View):
CreateView

2023-09-14 22:07 UTC, vickovtu commented on Users/views.py
> +        if user is not None:
if user:

2023-09-14 22:07 UTC, vickovtu commented on Users/views.py
> +class LibrarianMenuView(View):
TemplateView

2023-09-20 17:39 UTC, shorodilov requested changes
Виправ оте що Віктор написав.
Загалом - нормально.
Але за порушення PEP-8 будуть бити по руках.

2023-09-29 15:26 UTC, DashaKS25 commented
Я виправила те на що були зауваження .

2023-10-09 19:46 UTC, shorodilov approved these changes
lgtm

2023-10-10 10:55 UTC, merged